# Generated by Django 6.0 on 2026-02-01 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='authors',
            new_name='author',
        ),
    ]
